services:
  website:
    build: ./frontend
    ports:
      - 3000:80
      - 3001:443

  flask-app:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: postgres:14.9-alpine
    healthcheck: # healthcheck is used to make sure Postgres is running before other services that depend on it can run.
      test: [ "CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
volumes:
  postgres_db: